# The default config embedded in the festoji binary.
---
default: ğŸš

rules:
- name: Xmas
  emoji: ğŸ„
  span: 14
  month: 12
  day: 25
- name: Thanksgiving
  emoji: ğŸ¦ƒ
  span: 7
  month: 11
  week: 4
  weekday: 4
- name: New Year's
  emoji: ğŸ¾
  span: 5
  month: 1
  day: 1
- name: Valentine's Day
  emoji: â¤ï¸
  span: 7
  month: 2
  day: 14
- name: Halloween
  emoji: ğŸƒ
  span: 7
  month: 10
  day: 31
- name: Andrew's Public Birthday
  emoji: ğŸ«¥
  span: 1
  month: 1
  day: 11
- name: Simon's Public Birthday
  emoji: ğŸ˜›
  span: 1
  month: 1
  day: 13